version: "3"

services:
  server:
    image: lll:2.0
    build: .
    volumes:
      - ./nginx:/etc/nginx
    container_name: serveR

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx2:/etc/nginx
    depends_on:
      - server